env:
  global:
    - FDB_VERSION="6.2.7"
addons:
  apt:
    packages:
      - build-essential
      - python-dev
      - python-pip

cache:
  directories:
    - _build
    - deps

before_install:
  - |
    if [ $TRAVIS_OS_NAME = linux ]; then
      wget "https://www.foundationdb.org/downloads/$FDB_VERSION/ubuntu/installers/foundationdb-clients_$FDB_VERSION-1_amd64.deb"
      sudo dpkg -i "foundationdb-clients_$FDB_VERSION-1_amd64.deb"
      wget "https://www.foundationdb.org/downloads/$FDB_VERSION/ubuntu/installers/foundationdb-server_$FDB_VERSION-1_amd64.deb"
      sudo dpkg -i "foundationdb-server_$FDB_VERSION-1_amd64.deb"
    else
      brew install elixir
      wget "https://www.foundationdb.org/downloads/$FDB_VERSION/macOS/installers/FoundationDB-$FDB_VERSION.pkg"
      sudo installer -pkg "FoundationDB-$FDB_VERSION.pkg" -target /
      mix local.rebar --force
      mix local.hex --force
      mix deps.get
    fi

matrix:
  include:
    - language: elixir
      otp_release: 20.3
      elixir: 1.6
      os: linux
      env: DIALYZER=true
    - language: elixir
      otp_release: 20.3
      elixir: 1.6
      os: linux
      env: BINDINGS_TEST=true
    - language: elixir
      otp_release: 21.0
      elixir: 1.6
      os: linux
    - language: elixir
      otp_release: 21.0
      elixir: 1.7
      os: linux
    - language: elixir
      otp_release: 21.0
      elixir: 1.8
      os: linux
      env: VERIFY_FORMAT=true
    - os: osx

script:
  - make
  - |
    if [ "VERIFY_FORMAT" = "true" ]; then
      mix format --check-formatted
    fi
  - mix compile --force --warnings-as-errors
  - mix test --trace --include integration
  - if [ "$DIALYZER" = "true" ]; then travis_wait mix dialyzer --halt-exit-status; fi
  - |
    if [ "$BINDINGS_TEST" = "true" ]; then
      curl -L "https://github.com/apple/foundationdb/archive/$FDB_VERSION.tar.gz" > foundation.tar.gz
      tar -xf foundation.tar.gz
      rm foundation.tar.gz
      mv foundationdb-$FDB_VERSION foundationdb
      cd foundationdb
      patch -p1 < ../test/foundationdb.patch
      cd ..
      pip install --user "http://www.foundationdb.org/downloads/$FDB_VERSION/bindings/python/foundationdb-$FDB_VERSION.tar.gz"
      pip show foundationdb
      ./test/loop.sh
    fi
